import localFont from "next/font/local";
import "./globals.css";
import Link from "next/link";
import NavBar from "./components/navbar/navbar";
import Footer from "./components/footer/footer";
import icon from "../public/images/main4.jpg"
const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <title>ST PIZZA </title>
      </head>
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased    w-[95%] mx-auto xl:w-[81%]`}>
        <NavBar />
        {children}
       <Footer/>
      </body>
    </html>
  );
}
